name: Backend - Firebase Cloud Functions

on:
  push:
    branches:
    - master
    paths:
      - 'backend/**'
      - '.github/workflows/cloud-functions.yml'

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./backend
